#if !canImport(ObjectiveC)
import XCTest

extension NARS_Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NARS_Tests = [
        ("testCompounds", testCompounds),
        ("testExample", testExample),
        ("testWrappedBag", testWrappedBag),
    ]
}

extension Parsing_Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Parsing_Tests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

extension Single_Step {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Single_Step = [
        ("testMultiStep", testMultiStep),
        ("testNal1_00", testNal1_00),
        ("testNal1_01", testNal1_01),
        ("testNal1_02", testNal1_02),
        ("testNal1_03", testNal1_03),
        ("testNal1_04", testNal1_04),
        ("testNal1_05", testNal1_05),
        ("testNal1_06", testNal1_06),
        ("testNal1_07", testNal1_07),
        ("testNal2_00", testNal2_00),
        ("testNal2_01", testNal2_01),
        ("testNal2_02", testNal2_02),
        ("testNal2_03", testNal2_03),
        ("testNal2_04", testNal2_04),
        ("testNal2_05", testNal2_05),
        ("testNal2_06", testNal2_06),
        ("testNal2_07", testNal2_07),
        ("testNal2_08", testNal2_08),
        ("testNal2_10", testNal2_10),
        ("testNal2_11", testNal2_11),
        ("testNal2_12", testNal2_12),
        ("testNal2_13", testNal2_13),
        ("testNal2_14", testNal2_14),
        ("testNal2_15", testNal2_15),
        ("testNal2_16", testNal2_16),
        ("testNal2_17", testNal2_17),
        ("testNal2_18", testNal2_18),
        ("testNal3_00", testNal3_00),
        ("testNal3_01", testNal3_01),
        ("testNal3_04", testNal3_04),
        ("testNal3_05", testNal3_05),
        ("testNal3_08", testNal3_08),
        ("testNal3_09", testNal3_09),
        ("testNal3_10", testNal3_10),
        ("testNal3_11", testNal3_11),
        ("testNal7_00", testNal7_00),
        ("testNal7_01", testNal7_01),
        ("testNal7_02", testNal7_02),
        ("testNal7_X", testNal7_X),
        ("testSample", testSample),
        ("testVari", testVari),
        ("testVari2", testVari2),
        ("testVari3", testVari3),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NARS_Tests.__allTests__NARS_Tests),
        testCase(Parsing_Tests.__allTests__Parsing_Tests),
        testCase(Single_Step.__allTests__Single_Step),
    ]
}
#endif
